require("plugin_config.nvim-tree")
require("plugin_config.lua-line")
require("plugin_config.tree-sitter")
require("plugin_config.telescope")
require("plugin_config.cmp")
require("plugin_config.mason")
require("plugin_config.vimtex")
require("plugin_config.colorscheme")
require("plugin_config.mini-comment")
require("plugin_config.git-signs")
-- require("plugin_config.mini-pairs")
require("plugin_config.mini-sessions")
require 'colorizer'.setup()
